package co.com.intergrupo.cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2014-01-20T16:01:43.157-05:00
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://jaxws.intergrupo.com.co/", name = "InterfaceWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface InterfaceWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "vehiculoReportado", targetNamespace = "http://jaxws.intergrupo.com.co/", className = "co.com.intergrupo.cxf.VehiculoReportado")
    @WebMethod(action = "urn:vehiculoReportado")
    @ResponseWrapper(localName = "vehiculoReportadoResponse", targetNamespace = "http://jaxws.intergrupo.com.co/", className = "co.com.intergrupo.cxf.VehiculoReportadoResponse")
    public boolean vehiculoReportado(
        @WebParam(name = "placa", targetNamespace = "")
        java.lang.String placa
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saludo", targetNamespace = "http://jaxws.intergrupo.com.co/", className = "co.com.intergrupo.cxf.Saludo")
    @WebMethod
    @ResponseWrapper(localName = "saludoResponse", targetNamespace = "http://jaxws.intergrupo.com.co/", className = "co.com.intergrupo.cxf.SaludoResponse")
    public java.lang.String saludo(
        @WebParam(name = "nombre", targetNamespace = "")
        java.lang.String nombre
    );

    @WebResult(name = "vehiculo", targetNamespace = "")
    @RequestWrapper(localName = "consultarVehiculo", targetNamespace = "http://jaxws.intergrupo.com.co/", className = "co.com.intergrupo.cxf.ConsultarVehiculo")
    @WebMethod(action = "urn:consultarVehiculo")
    @ResponseWrapper(localName = "consultarVehiculoResponse", targetNamespace = "http://jaxws.intergrupo.com.co/", className = "co.com.intergrupo.cxf.ConsultarVehiculoResponse")
    public co.com.intergrupo.cxf.Vehiculo consultarVehiculo(
        @WebParam(name = "placa", targetNamespace = "")
        java.lang.String placa
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "vehiculoAlDiaConImpuesto", targetNamespace = "http://jaxws.intergrupo.com.co/", className = "co.com.intergrupo.cxf.VehiculoAlDiaConImpuesto")
    @WebMethod(action = "urn:vehiculoAlDiaConImpuesto")
    @ResponseWrapper(localName = "vehiculoAlDiaConImpuestoResponse", targetNamespace = "http://jaxws.intergrupo.com.co/", className = "co.com.intergrupo.cxf.VehiculoAlDiaConImpuestoResponse")
    public boolean vehiculoAlDiaConImpuesto(
        @WebParam(name = "placa", targetNamespace = "")
        java.lang.String placa
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "registradoRunt", targetNamespace = "http://jaxws.intergrupo.com.co/", className = "co.com.intergrupo.cxf.RegistradoRunt")
    @WebMethod(action = "urn:registradoRunt")
    @ResponseWrapper(localName = "registradoRuntResponse", targetNamespace = "http://jaxws.intergrupo.com.co/", className = "co.com.intergrupo.cxf.RegistradoRuntResponse")
    public boolean registradoRunt(
        @WebParam(name = "placa", targetNamespace = "")
        java.lang.String placa
    );
}
